// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Annotator_AnnotatorLib_Image_BODY

/************************************************************
 Image class body
 ************************************************************/

// include associated header file
#include "AnnotatorLib/Image.h"

// Derived includes directives

namespace AnnotatorLib {

// static attributes (if any)

}// of namespace AnnotatorLib

/************************************************************
 End of Image class body
 ************************************************************/
