version: 1.0.{build}
os: Visual Studio 2015
platform: Win32

branches:
  only:
   - master

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

clone_folder: c:\dev\src

init:
- env
- set POCO_INSTALL_PREFIX=%PROGRAMFILES%\Poco
- set PATH=C:\MinGW\bin;%PATH%;%POCO_INSTALL_PREFIX%\bin

install:
 - cmd: echo "Downloading conan..."
 - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
 - cmd: pip.exe install conan
 - cmd: conan user
 - cmd: conan --version

before_build:
  - cd c:\dev\src
  - md build
  - cmd: conan install Poco/1.7.3@lasote/stable -s arch="x86" -s build_type="Release" -s compiler="Visual Studio" -s compiler.runtime="MD" -s compiler.version="14" -s os="Windows" -o enable_netssl="True" -o enable_net="True" -o enable_data_sqlite="True" -o enable_pocodoc="False" -o enable_pagecompiler="False" -o enable_sevenzip="False" -o enable_json="True" -o enable_data_mysql="False" -o enable_util="True" -o force_openssl="True" -o shared="False" -o enable_tests="False" -o enable_pdf="False" -o enable_data="True" -o enable_data_odbc="False" -o enable_cppparser="False" -o enable_pagecompiler_file2page="False" -o poco_unbundled="False" -o enable_zip="True" -o enable_netssl_win="True" -o enable_mongodb="True" -o enable_apacheconnector="False" -o enable_crypto="True" -o enable_xml="True" 

build_script:
  - cd c:\dev\src\build
  - cmake .. -G %makefiles% -DCMAKE_INSTALL_PREFIX="c:/dev/install"
  - cmake --build . --config %CONFIGURATION%

test: off
