version: 1.0.{build}
os: Visual Studio 2015
platform: x64

branches:
  only:
   - master

clone_folder: c:\dev\src

init:
- env
- set POCO_INSTALL_PREFIX=%PROGRAMFILES%\Poco
- set PATH=C:\MinGW\bin;%PATH%;%POCO_INSTALL_PREFIX%\bin

install:
 - cmd: echo "Downloading conan..."
 - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
 - cmd: pip.exe install conan
 - cmd: conan user
 - cmd: conan --version

before_build:
  - cd c:\dev\src
  - md build
  - cd build
  - cmd: conan install -g cmake Boost/1.60.0@lasote/stable -s arch="x86_64" -s build_type="Release" -s compiler="Visual Studio" -s compiler.runtime="MD" -s compiler.version="14" -s os="Windows" -o without_coroutine2="False" -o without_atomic="False" -o header_only="False" -o without_container="False" -o without_system="False" -o without_type_erasure="False" -o without_random="False" -o without_math="False" -o without_thread="False" -o without_graph="False" -o without_filesystem="False" -o without_log="False" -o without_graph_parallel="False" -o without_mpi="False" -o shared="True" -o python="False" -o without_locale="False" -o without_chrono="False" -o without_signals="False" -o without_coroutine="False" -o without_wave="False" -o without_iostreams="False" -o without_regex="False" -o without_context="False" -o without_serialization="False" -o without_test="False" -o without_exception="False" -o without_date_time="False" -o without_program_options="False" -o without_timer="False" 
  - cmd: conan install -g cmake Poco/1.7.3@lasote/stable -s arch="x86_64" -s build_type="Release" -s compiler="Visual Studio" -s compiler.runtime="MT" -s compiler.version="14" -s os="Windows" -o enable_netssl="True" -o enable_net="True" -o enable_data_sqlite="True" -o enable_pocodoc="False" -o enable_pagecompiler="False" -o enable_sevenzip="False" -o enable_json="True" -o enable_data_mysql="False" -o enable_util="True" -o force_openssl="True" -o shared="False" -o enable_tests="False" -o enable_pdf="False" -o enable_data="True" -o enable_data_odbc="False" -o enable_cppparser="False" -o cxx_14="False" -o enable_pagecompiler_file2page="False" -o poco_unbundled="False" -o enable_zip="True" -o enable_netssl_win="True" -o enable_mongodb="True" -o enable_apacheconnector="False" -o enable_crypto="True" -o enable_xml="True"
  - cmd: conan install -g cmake opencv/3.1.0-1@lasote/vcpkg -s arch="x86_64" -s build_type="Release" -s compiler="Visual Studio" -s compiler.runtime="MD" -s compiler.version="14" -s os="Windows" 

build_script:
  - cd c:\dev\src\build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DOPTION_CONAN_PACKAGES=1
  - cmake --build . --config Release

test: off
