language:
 - cpp

os:
 - linux
dist: trusty
sudo: required
compiler:
     - gcc
     - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - sourceline: 'ppa:snappy-dev/tools'
  
  packages:
   - gcc-5
   - g++-5
   - build-essential
   - cmake
   - git
   - rpm
   - libgtk2.0-dev
   - pkg-config
   - libavcodec-dev
   - libavformat-dev
   - libswscale-dev
   - python-dev
   - python-numpy
   - libtbb2
   - libtbb-dev
   - libjpeg-dev
   - libpng-dev
   - libtiff-dev
   - libjasper-dev
   - libdc1394-22-dev
   - libboost-all-dev
   - libpoco-dev
   - libmysqlclient-dev
   - libmongo-client-dev
   - lcov
   - texlive-fonts-recommended
   - texlive-latex-extra
   - texlive-fonts-extra
   - dvipng
   - texlive-latex-recommended
   - texlive-full
   - snapcraft
   - snap

install:
 - sudo pip install cpp-coveralls
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
         sudo apt-get update -qq
      && sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev libqt5webkit5-dev
      ;
   else
         brew tap homebrew/science
      && brew update
      && brew install cmake
      && brew install qt5
      && brew install opencv3 --with-contrib
      ;
   fi

before_script:
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
 - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
 - gcc -v
 - g++ -v

 - wget http://www.cmake.org/files/v3.6/cmake-3.6.0.tar.gz
 - tar xf cmake-3.6.0.tar.gz
 - cd cmake-3.6.0
 - ./configure
 - make
 - sudo make install
 - cd ..

 - curl -sL https://github.com/Itseez/opencv/archive/3.1.0.zip > opencv.zip
 - unzip opencv.zip
 - cd opencv-3.1.0
 - mkdir build install
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_FFMPEG=OFF -DWITH_IPP=OFF ..
 - make -j8
 - sudo make install
 - cd ../../

 - git clone https://github.com/pocoproject/poco
 - sed -i 's#mysqlclient_r#mysqlclient mysqlclient_r#g' poco/cmake/FindMySQL.cmake
 - cd poco
 - mkdir -p build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release .. && make -j3 && sudo make install && sudo ldconfig
 - cd ../..


 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$CXX -DOPTION_BUILD_TESTS=1 -DOPTION_BUILD_DOCS=1 -DCMAKE_BUILD_TYPE=Coverage ..
script:
 - make -j4
 - make pack

after_success:
  - make annotatorlib_coverage
  - cd ..
  - coveralls --root "." -E ".*/cmake-3.6.0/.*" -E ".*/opencv-3.1.0/.*" -E ".*/poco/.*" -E ".*/build/gtest/.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
   - $TRAVIS_BUILD_DIR/build/*.deb
   - $TRAVIS_BUILD_DIR/build/*.rpm
   - $TRAVIS_BUILD_DIR/build/docs/manual/annotatorlib.pdf
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b9437d0824d4035cf45
    on_success: change
    on_failure: always
    on_start: never
