version: '2'
services:
  annotatorlib:
  # image:chriamue/annotatorlib:cpu
    build: cpu
    volumes:
     - '${HOME}/:/home/user/'
  annotatorlibgpu:
  # image:chriamue/annotatorlib:gpu
    build: gpu
    volumes:
     - '${HOME}/:/home/user/'
    devices:
     - /dev/nvidia0
  annotatorlibipynb:
  # image:chriamue/annotatorlib:ipynb
    build: ipynb
    volumes:
     - '${HOME}/:/home/user/'
    ports:
     - 8888:8888