// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Annotator_AnnotatorLib_Loader_SQLLoader_BODY

/************************************************************
 SQLLoader class body
 ************************************************************/

// include associated header file
#include "AnnotatorLib/Loader/SQLLoader.h"

// Derived includes directives

namespace AnnotatorLib {
namespace Loader {

Annotation SQLLoader::getAnnotations()
{
    return Annotation();
}

void SQLLoader::setPath(std::string path)
{

}

StorageType SQLLoader::getType()
{
    return AnnotatorLib::StorageType::SQL;
}

void SQLLoader::loadSession(Session *session)
{

}

// static attributes (if any)

}// of namespace Loader
} // of namespace AnnotatorLib

/************************************************************
 End of SQLLoader class body
 ************************************************************/
