// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ANNOTATOR_ANNOTATORLIB_SAVER_XMLSAVER_H
#define ANNOTATOR_ANNOTATORLIB_SAVER_XMLSAVER_H

/************************************************************
 XMLSaver class header
 ************************************************************/
#include <QDomDocument>
#include <QDomElement>

#include <AnnotatorLib/annotatorlib_api.h>
#include "AnnotatorLib/Saver/Pkg_Saver.h"

#include "AnnotatorLib/Saver/AbstractSaver.h"

namespace AnnotatorLib {

class Frame;

namespace Saver {

/************************************************************/
/**
 *
 */
class ANNOTATORLIB_API XMLSaver : public AbstractSaver {
  // AbstractSaver interface
 public:
  void saveFrame( const AnnotatorLib::Frame *frame, const AnnotatorLib::Session *session);
  void saveAnnotation(const Annotation annotation);
  void setPath(std::string path);
  StorageType getType();
  void saveSession(const AnnotatorLib::Session *session);
  bool close();

 protected:
  QDomElement meta(const AnnotatorLib::Frame *frame);
  QDomElement fromObject( const AnnotatorLib::Object *object,
                          const AnnotatorLib::Frame *frame);

  std::string path;

  QDomDocument document;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

}  // of namespace Saver
}  // of namespace AnnotatorLib

/************************************************************
 End of XMLSaver class header
 ************************************************************/

#endif
