// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ANNOTATOR_ANNOTATORALGO_ANNOTATORALGOINTERFACE_H
#define ANNOTATOR_ANNOTATORALGO_ANNOTATORALGOINTERFACE_H

/************************************************************
 AnnotatorAlgoInterface class header
 ************************************************************/
#include <vector>
#include <opencv2/core/core.hpp>

#include "AnnotatorLib/Commands/Command.h"
#include <AnnotatorLib/annotatorlib_api.h>
#include "AnnotatorLib/Image.h"

namespace AnnotatorLib {
    class Annotation;
    class Frame;
    class Object;
    class Session;
}

namespace AnnotatorAlgo {

/************************************************************/
/**
 *
 */
class ANNOTATORLIB_API AnnotatorAlgoInterface {
public:

    /**
     *
     * @param image
     */
    virtual void addPositive(cv::Mat image) = 0;

    /**
     *
     * @param image
     */
    virtual void addNegative(cv::Mat image) = 0;

    /**
     *
     * @param image
     */
    virtual bool setFrame(AnnotatorLib::Frame *frame, cv::Mat image) = 0;

    /**
     *
     * @param object
     */
    virtual void setObject(AnnotatorLib::Object /*in*/*object) = 0;

    virtual AnnotatorLib::Object * getObject() = 0;

    /**
     * @brief setLastAnnotation
     * @param annotation
     */
    virtual void setLastAnnotation(AnnotatorLib::Annotation *annotation) = 0;

    virtual std::vector<AnnotatorLib::Commands::Command*> getCommands() = 0;

    /**
     *
     * @return annotation
     */
    virtual AnnotatorLib::Annotation *getAnnotation() = 0;

    virtual void setSession(AnnotatorLib::Session * session) = 0;



};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace AnnotatorAlgo

/************************************************************
 End of AnnotatorAlgoInterface class header
 ************************************************************/

#endif
