// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ANNOTATOR_ANNOTATORLIB_IMAGEFOLDER_H
#define ANNOTATOR_ANNOTATORLIB_IMAGEFOLDER_H

/************************************************************
 ImageFolder class header
 ************************************************************/

#include <boost/filesystem.hpp>
#include <vector>

#include <AnnotatorLib/AnnotatorLibDatastructs.h>
#include <AnnotatorLib/annotatorlib_api.h>

#include <AnnotatorLib/ImageSet.h>

namespace AnnotatorLib {

/************************************************************/
/**
 *
 */
class ANNOTATORLIB_API ImageFolder : public ImageSet {
 public:
  ImageFolder(std::string path);

  /**
   *
   * @return type
   */
  virtual ImageSetType getType();

  /**
   *
   * @param frame
   * @return image
   */
  virtual Image getImage(unsigned int /*in*/ frame);

  virtual bool gotoPosition(long position);

  virtual long getPosition();

  /**
   *
   * @return next
   */
  virtual bool hasNext();

  /**
   *
   * @return image
   */
  virtual Image next();

  /**
   *
   * @return size
   */
  virtual unsigned int size();

  virtual std::string getPath();

  virtual bool equals(ImageSet *other);

 protected:
  void loadFolder();

  std::string path;

  long position = 0;
  std::vector<boost::filesystem::path> images;
  std::vector<boost::filesystem::path>::const_iterator imgIter;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

}  // of namespace AnnotatorLib

/************************************************************
 End of ImageFolder class header
 ************************************************************/

#endif
