// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ANNOTATOR_ANNOTATORLIB_IMAGE_H
#define ANNOTATOR_ANNOTATORLIB_IMAGE_H

/************************************************************
 Image class header
 ************************************************************/
#include <opencv2/core/core.hpp>
#include <AnnotatorLib/annotatorlib_api.h>
#include <AnnotatorLib/AnnotatorLibDatastructs.h>

namespace AnnotatorLib {

/************************************************************/
/**
 * 
 */

typedef cv::Mat Image;

/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace AnnotatorLib

/************************************************************
 End of Image class header
 ************************************************************/

#endif
